config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :videos

  root 'videos#index'
  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :videos
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :file, FileUploader
end

app/models/video.rb
class Video < ActiveRecord::Base
	validates :title, presence: true, uniqueness: true
	validates :description, presence: true
	belongs_to :user
	mount_uploader :file, FileUploader
end

app/controllers/api/base.rb
module API
	class Base < Grape::API
		mount API::V1::Base
	end
end

app/controllers/api/v1/base.rb
require "grape-swagger"

module API 
	module V1
		class Base < Grape::API
			mount API::V1::Videos
			#mount API::V1::AnotherResource
			#add_swagger_documentation(
			#	api_version: "v1",
			#	hide_documentation_path: true,
			#	mount_path: "/api/v1/swagger_doc", 
			#	hide_format: true
			#)
		end
	end
end

app/controllers/api/v1/defaults.rb
module API
	module V1
		module Defaults
			extend ActiveSupport::Concern

			included do
				prefix "api"
				version "v1", using: :path
				default_format :json
				format :json
				formatter :json, Grape::Formatter::ActiveModelSerializers

        		helpers do
          			def permitted_params
           				@permitted_params ||= declared(params, include_missing: false)
          			end

          			def logger
            			Rails.logger
          			end
        		end
					
				rescue_from ActiveRecord::RecordNotFound do |e|
					error_response(message: e.message, status: 404)
				end
				
				rescue_from ActiveRecord::RecordInvalid do |e|
				    error_response(message: e.message, status: 422)
				end		
			end
		end
	end
end

app/controllers/api/v1/videos.rb
module API
	module V1
		class Videos < Grape::API
			include API::V1::Defaults

			resource :videos do
				desc "Return all videos"
				get "", root: :videos do
					Video.all
				end
				
				desc "Return a video"
				params do
					requires :id, type: String, desc: "ID of the video"
				end

				get ":id", root: "video" do
					Video.where(id:permitted_params[:id]).first!
				end
			end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  #before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = current_user.videos
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = current_user.videos.build(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :description, :file, :remote_file_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VidUpload</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>

</body>
</html>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <p id='file_upload' style='display:none;'>
    <%= f.file_field :file %>
  </p>
 <p id='file_url' style='display:none;'>

    <%= f.label :remote_file_url, "or file URL" %><br />
    <%= f.text_field :remote_file_url %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>File</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= video.file %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form' %>
<select>
  <option value="file_upload">Upload from local computer</option>
  <option value="file_url">Upload from remote url</option>
</select>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Title:</strong>
	<%= @video.title %>
</p>

<p>
	<strong>Description:</strong>
	<%= @video.description %>
</p>

<p>
	<strong>File:</strong>
	<% if @video.remote_file_url.nil?%>
	
	<%= video_tag([@video.file], :size => "320x240", :controls => true) %>
	<% else %>
	<%= video_tag([@video.remote_file_url], :size => "320x240", :controls => true) %>
	<% end %>


</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>